### ISSUE TITLE
Product rating & review

### ISSUE THREAD

**Issue by duongdev** [targeek/storelammoc-marketplace#96]
# Purpose

- Allow customers who bought a product to rate & review that product.
- A rating should contain: `rate`, `title`, `content`, `target`: an identity of the rating target. Eg: `product-{productId}` for products, `co-{orderId}` for orders.
- Given a product, be able to get its average rating and how many ratings submitted.
- Count & filter for ratings by `rate` (stars).
- Sort by rate or date.
- Pagination.
- In dashboard: ?

# Specifications

- A customer can submit a rating review IFF he has bought that product more than once between the last time he bought it and the current moment.

**Comment by duongdev** [comment]
@nguyenthienthanh please complete the **Implementation** part before start working

**Comment by nguyenthienthanh** [comment]
# Context

- Khi khách hàng vào xem một sản phẩm, khách hàng sẽ được phép để lại đánh giá của mình nếu đã mua sản phẩm đó gồm phần `rate` và `content`, thể hiện mức độ hài lòng được tính bằng ⭐ (tối đa 5 sao) kèm theo phần bình luận chi tiết về sản phẩm (nếu có).
- Khi khách hàng vào xem đơn hàng đã mua, khách hàng cũng có thể để lại đánh giá của mình cho mỗi sản phẩm đã mua trong đơn hàng.

**Comment by nguyenthienthanh** [comment]
# Implementation

- Model name: `RatingReview`.
- Fields: 
  - rate: (number) một số nguyên dương thể hiện số sao đánh giá
  - title: (string) tiêu đề phần đánh giá do người dùng đặt hoặc mô tả số sao đánh giá (Kém, Không hài lòng, Hài lòng, Rất hài lòng, Tuyệt vời)
  - content: (string) nội dung đánh giá của khách hàng đối với sản phẩm (có thể có hoặc không)
  - target: (string) gồm 2 phần với định dạng sau `type-id`
    - type: đối tượng được đánh giá, có thể là `product`, `order`
    - id: mã của đối tượng được đánh giá `productId`, `orderId`

**Comment by nguyenthienthanh** [comment]
# Service
## checkIfUserPossibleToRateProduct
### Input
- userId: (string) mã người dùng
- productId: (string) mã sản phẩm
- variantId: (string) mã phiên bản sản phẩm
### Validation
- Nếu `userId` không được nhập thì thông báo lỗi `userId is a required field`
- Nếu `userId` không phải là `string` thì thông báo lỗi `userId must be a string type`
- Nếu `productId` không phải là `string` thì thông báo lỗi `productId must be a string type`
- Nếu `variantId` không phải là `string` thì thông báo lỗi `variantId must be a string type`
- Nếu `productId` và `variantId` không được nhập thì thông báo lỗi `there is required at least field productId, variantId`
### Process
- Với `userId` tìm `customer` tương ứng
- Gọi `countCustomerProductHistories` với `filter` là 
  - customerIdentities: là [`customer.id`, `user.phone`]
  - productId: là `productId` nếu có
  - variantId: là `variantId` nếu có
- Kết quả của `countCustomerProductHistories` nếu lớn hơn 0 thì trả về `True` và `False` nếu <= 0
### Output
- True: Khách hàng có thể đánh giá sản phẩm | phiên bản sản phẩm
- False: Khách hàng không thể đánh giá sản phẩm | phiên bản sản phẩm

# Mutation
### Input
- productId: (String) mã sản phẩm
- variantId: (String) mã phiên bản sản phẩm
### Authentication
- Nếu người dùng chưa đăng nhập thì thông báo lỗi `unauthorized`
### Input
- Nếu `productId` không phải là `string` thì thông báo lỗi `productId must be a string type`
- Nếu `variantId` không phải là `string` thì thông báo lỗi `variantId must be a string type`
- Nếu `productId` và `variantId` không được nhập thì thông báo lỗi `there is required at least field productId, variantId`
### Process
Gọi `checkIfUserPossibleToRateProduct` với input là
  - userId: là `context.user.id`
  - productId: từ input
  - variantId: từ input
### Output
- True: Khách hàng có thể đánh giá sản phẩm | phiên bản sản phẩm
- False: Khách hàng không thể đánh giá sản phẩm | phiên bản sản phẩm

**Comment by nguyenthienthanh** [comment]
# Service
## createRatingReview
### Input
- targetType(required): [string] Đối tượng được đánh giá
- targetId(required): [string] Mã đối tượng được đánh giá
- rate(required): [string] Cấp độ đánh giá
- title(required): [string] Tiêu đề đánh giá
- content(optional): [string] Nội dung đánh giá
### Validation
- Nếu `targetType` không được nhập thì thông báo lỗi `targetType is a required field`
- Nếu `targetType` không phải là `string` thì thông báo lỗi `targetType must be a string type`
- Nếu `targetId` không được nhập thì thông báo lỗi `targetId is a required field`
- Nếu `targetId` không phải là `string` thì thông báo lỗi `targetId must be a string type`
- Nếu `rate` không được nhập thì thông báo lỗi `rate is a required field`
- Nếu `rate` không phải là số nguyên dương thì thông báo lỗi `rate must be a positive number`
- Nếu `title` không được nhập thì thông báo lỗi `title is a required field`
- Nếu `title` không phải là `string` thì thông báo lỗi `title must be a string type`
- Nếu `content` không phải là `string` thì thông báo lỗi `content must be a string type`
### Process
Tạo `RatingReview` với dữ liệu
- target: được tạo ra theo cú pháp `${targetType}-${targetId}`
- rate
- title
- content
### Output
`RatingReview` đã tạo thành công

# Constant
## FRIENDLY_PRODUCT_RATINGS
- Type: Array
- Values: [ 'Rất tệ', 'Không hài lòng', 'Hài lòng', 'Rất hài lòng', 'Tuyệt vời' ]

# Mutation
## rateProduct
### Input
- productId(required): [String] Mã sản phẩm
- rate(required): [Int] Cấp độ đánh giá, tối đa 5 cấp độ
- title(optional): [String] Tiêu đề
- content(optional): [String] Nội dung đánh giá
### Authorization
- Nếu người dùng chưa đăng nhập thì thông báo lỗi `unauthorized`
### Validation
- Nếu `productId` không được nhập thì thông báo lỗi `productId is a required field`
- Nếu `productId` không phải là `string` thì thông báo lỗi `productId must be a string type`
- Nếu `rate` không được nhập thì thông báo lỗi `rate is a required field`
- Nếu `rate` không phải là số nguyên dương thì thông báo lỗi `rate must be a positive number`
- Nếu `rate` lớn hơn 5 thì thông báo lỗi `rate must be less than 5`
- Nếu `title` không phải là `string` thì thông báo lỗi `title must be a string type`
- Nếu `content` không phải là `string` thì thông báo lỗi `content must be a string type`
### Process
- Nếu `title` không được nhập thì `title` sẽ là giá trị từ `FRIENDLY_PRODUCT_RATINGS[rate]`
- Gọi `createRatingReview` với input
  - targetType: 'product'
  - targetId: productId
  - rate
  - title
  - content
### Output
`RatingReview` đã tạo được

**Comment by nguyenthienthanh** [comment]
# Service 
## getAverageAndTotalRating
### Input
- targetType(required): [string] Đối tượng được đánh giá
- targetId(required): [string] Mã đối tượng được đánh giá
### Validation
- Nếu `targetType` không được nhập thì thông báo lỗi `targetType is a required field`
- Nếu `targetType` không phải là `string` thì thông báo lỗi `targetType must be a string type`
- Nếu `targetId` không được nhập thì thông báo lỗi `targetId is a required field`
- Nếu `targetId` không phải là `string` thì thông báo lỗi `targetId must be a string type`
### Process
(Các cú pháp và câu lệnh sử dụng dựa theo `mongodb`)
- Gọi `generateRatingReviewTarget` để tạo `target` với đầu vào
  - targetType
  - targetId
- Gọi hàm `aggregate` với `pipeline` như sau để tính số điểm đánh giá trung bình và tổng số lượt đánh giá
```json
[
  {
    $match: {
      target,
    },
  },
  {
    $group: {
      _id: '$target',
      total: { $sum: 1 },
      average: { $avg: '$rate' },
    },
  },
]
```
### Output
- total: [number] Tổng số lượt đánh giá
- average: [float] Đánh giá trung bình

# Query
## averageAndTotalProductRating
### Input
- productId(required): [String] Mã sản phẩm
### Validation
- Nếu `productId` không được nhập thì thông báo lỗi `productId is a required field`
- Nếu `productId` không phải là `string` thì thông báo lỗi `productId must be a string type`
### Process
- Gọi `getAverageAndTotalRating` với đầu vào
  - targetType: 'product'
  - targetId: productId
### Output
- total: [number] Tổng số lượt đánh giá
- average: [float] Đánh giá trung bình

**Comment by nguyenthienthanh** [comment]
# Service
## countRatingReviewByRate
### Input
- targetType(required): [string] Đối tượng được đánh giá
- targetId(required): [string] Mã đối tượng được đánh giá
### Validation
- Nếu `targetType` không được nhập thì thông báo lỗi `targetType is a required field`
- Nếu `targetType` không phải là `string` thì thông báo lỗi `targetType must be a string type`
- Nếu `targetId` không được nhập thì thông báo lỗi `targetId is a required field`
- Nếu `targetId` không phải là `string` thì thông báo lỗi `targetId must be a string type`
### Process
(Các cú pháp và câu lệnh sử dụng dựa theo `mongodb`)
- Gọi `generateRatingReviewTarget` để tạo `target` với đầu vào
  - targetType
  - targetId
- Gọi hàm `aggregate` với `pipeline` như sau
```javascript
[
  {
    $group: {
      _id: '$rate',
      total: { $sum: 1 },
    },
  },
]
```
### Output
```javascript
{
  1: // Tổng số rate = 1,
  2: // Tổng số rate = 2,
  3: // Tổng số rate = 3,
  4: // Tổng số rate = 4,
  5: // Tổng số rate = 5,
  n: // Tổng số rate = n,
}
```

## transformRateObjectToArray
### Input
- total(required): [number] số hạng đánh giá
- ratingObject(required): [object] danh sách đánh giá theo định dạng `object`
### Validation
- Nếu `total` không được nhập thì thông báo lỗi `total is a required field`
- Nếu `total` không phải là số nguyên dương thì thông báo lỗi `total must be a positive number`
- Nếu `ratingObject` không được nhập thì thông báo lỗi `ratingObject is a required field`
- Nếu `ratingObject` không phải là object có dạng `{ [1-total]: number }` thì thông báo lỗi `ratingObject must be follow this format { [1-total]: number }`
### Process
- Tạo một mảng gồm `total` phần từ có giá trị là `0`
- Với mỗi phần tử của mảng, số hạng sẽ là thứ tự của phần từ cộng thêm `1`, thay đổi giá trị của phần tử tương ứng theo giá trị của `ratingObject[index + 1]`
- Công thức viết bằng `javascript`
```javascript
const initialRatings = new Array(total).fill(0)
const ratings = initialRatings.map((value, index) => {
  const totalRate = ratingObject[index + 1]
  if (totalRate) return totalRate
  return value
})
```

# Query
## numberOfProductRatingReviewByRate
### Input
- productId(required): [String] Mã sản phẩm
### Validation
- Nếu `productId` không được nhập thì thông báo lỗi `productId is a required field`
- Nếu `productId` không phải là `string` thì thông báo lỗi `productId must be a string type`
### Process
- Gọi `countRatingReviewByRate` với đầu vào
  - targetType: 'product'
  - targetId: productId
- Gọi `transformRateObjectToArray` với đầu vào là kết quả của `countRatingReviewByRate` và `total = 5`
### Output
- Danh sách gồm 5 phần tử thể hiện số lượt đánh giá cho mỗi hạng với phần tử đầu tiên là hạng 1 và phần tử cuối cùng là hạng 5

**Comment by nguyenthienthanh** [comment]
# Service
## getRatingReviews
### Input
- targetType(required): [string] Đối tượng được đánh giá
- targetId(optional): [string] Mã đối tượng được đánh giá
- rate(optional): [number] Số hạng đánh giá
- orderBy(optional): [string] thứ tự sắp xếp, một trong các thứ tự sau: `createdAt`, `reverse:createdAt`, `rate`, `reverse:rate`, mặc định là `reverse:createdAt`
- offset(optional): [number] Số lượng kết quả sẽ được bỏ qua, mặc định là 0
- limit(optional): [number] Số lượng kết quả được trả về, mặc định là 10
### Validation
- Nếu `targetType` không được nhập thì thông báo lỗi `targetType is a required field`
- Nếu `targetType` không phải là `string` thì thông báo lỗi `targetType must be a string type`
- Nếu `targetId` không được nhập thì thông báo lỗi `targetId is a required field`
- Nếu `targetId` không phải là `string` thì thông báo lỗi `targetId must be a string type`
- Nếu `rate` không phải là số nguyên dương thì thông báo lỗi `rate must be a positive number`
- Nếu `orderBy` không phải là `string` thì thông báo lỗi `orderBy must be a string type`
- Nếu `orderBy` không hợp lệ thì thông báo lỗi `orderBy must be one of the following values: createdAt, reverse:createdAt, rate, reverse:rate`
- Nếu `offset` không phải là số nguyên dương thì thông báo lỗi `offset must be a positive number`
- Nếu `limit` không phải là số nguyên dương thì thông báo lỗi `limit must be a positive number`
### Process
- Gọi `generateRatingReviewTarget` để tạo `target` với đầu vào
  - targetType
  - targetId
- Gọi `getSortByObject` để tạo `mongoose` sortBy object từ `orderBy`
- Tìm danh sách `RatingReview` từ các `filter` trên.
- Đồng thời đếm tất cả các `RatingReview` ứng với `filter`
### Output
- total: Tổng số lượng `RatingReview`
- prevOffset: offset trước đó
- currentOffset: offset hiện tại
- nextOffset: offset tiếp theo
- limit: Giới hạn
- edges: Danh sách `RatingReview`

# Query
## productRatingReviews
### Input
- productId(required): [String] mã sản phẩm
- rate(optional): [number] Số hạng đánh giá
- orderBy(optional): [string] thứ tự sắp xếp, một trong các thứ tự sau: `createdAt`, `reverse:createdAt`, `rate`, `reverse:rate`, mặc định là `reverse:createdAt`
- offset(optional): [number] Số lượng kết quả sẽ được bỏ qua, mặc định là 0
- limit(optional): [number] Số lượng kết quả được trả về, mặc định là 10
### Validation
- Nếu `productId` không được nhập thì thông báo lỗi `productId is a required field`
- Nếu `productId` không phải là `string` thì thông báo lỗi `productId must be a string type`
- Nếu `rate` không phải là số nguyên dương thì thông báo lỗi `rate must be a positive number`
- Nếu `orderBy` không phải là `string` thì thông báo lỗi `orderBy must be a string type`
- Nếu `orderBy` không hợp lệ thì thông báo lỗi `orderBy must be one of the following values: createdAt, reverse:createdAt, rate, reverse:rate`
- Nếu `offset` không phải là số nguyên dương thì thông báo lỗi `offset must be a positive number`
- Nếu `limit` không phải là số nguyên dương thì thông báo lỗi `limit must be a positive number`
### Process
- Gọi `getRatingReviews` với đầu vào
  - targetType: 'product'
  - targetId: productId
  - rate
  - orderBy
  - offset
  - limit
### Output
- total: Tổng số lượng `RatingReview`
- prevOffset: offset trước đó
- currentOffset: offset hiện tại
- nextOffset: offset tiếp theo
- limit: Giới hạn
- edges: Danh sách `RatingReview`

**Comment by nguyenthienthanh** [comment]
@duongdev I have completed the `implementation`, could you review?
