### ISSUE TITLE
Customer product history

### ISSUE THREAD

**Issue by nguyenthienthanh** [targeek/storelammoc-marketplace#97]
- This service will tracking products that customer has bought
# Purpose
- Với mỗi sản phẩm, cho biết số lượng đã bán ra
- Với mỗi sản phẩm, cho biết doanh thu đã bán ra
- Với mỗi sản phẩm, cho biết thời gian bán sản phẩm đó là khi nào
- Với mỗi sản phẩm, cho biết số lượng đã bán ra trong một khoảng thời gian nhất định (từ, đến)
- Với mỗi khách hàng, cho biết số lần mua hàng và số mặt hàng đã mua
- Với mỗi khách hàng, cho biết số lần mua hàng trong một khoảng thời gian nhất định (từ, đến)
- Với một sản phẩm, cho biết một khách hàng đã mua sản phẩm đó hay chưa
# Specifications
- Hệ thống sẽ chạy lặp lại trong một khoảng thời gian nhất định và lấy tất cả đơn hàng đã hoàn thành theo thời gian cập nhật trong khoảng thời gian kể từ lần chạy gần nhất đên hiện tại
- Với mỗi đơn hàng đã hoàn thành của mỗi khách hàng, sẽ trích xuất ra các sản phẩm và lưu lại sản phẩm, khách hàng, số lượng, đơn giá bán trên đơn hàng
# Context
- Khi khách hàng mua ở POS với số điện thoại mà số điện thoại đó chưa được đăng ký người dùng thì `customerIdentity` sẽ có giá trị là **số điện thoại**.
- Khi khách hàng đã hoàn thành đăng ký tài khoản với một số điện thoại thì hệ thống sẽ kiểm tra số điện thoại đã có mua hàng trên hệ thống hay chưa và tìm tất cả `CustomerProductHistory` có `customerIdentity` ứng với số điện thoại vừa tạo và cập nhật lại thành `customerId` vừa được đăng ký
# Implementation
## Model
- Model name: CustomerProductHistory
- Fields: customerIdentity(customerId | phone), product(id, name, image), variant(id, sku, image, price), customerOrder(id, createdAt, completedAt, customerAgencyOrderId), quantity
#### Input
- customerIdentity(string): Mã định danh khách hàng, có thể là `customerId` hoặc số điện thoại.
- product:
id(string of ObjectId): Id của sản phẩm
name(string): Tên sản phẩm tại thời điểm mua hàng
image(string): Hình ảnh đầu tiên trong danh sách hình ảnh của sản phẩm
- variant:
id(ObjectId string): Id của phiên bản sản phẩm
sku(string): SKU của phiên bản sản phẩm
image(string): Hình đại diện đầu tiên trong danh sách hình ảnh của phiên bản sản phẩm tại thời điểm mua hàng
price(Float): Đơn giá bán của phiên bản sản phẩm tại thời điểm mua hàng
- customerOrder:
id(string of ObjectId): Id của CustomerOrder
createdAt(Date): Thời gian tạo của CustomerOrder
completedAt(Date): Thời hoàn thành của CustomerOrder
- quantity(number): Tổng số lượng sản phẩm đã mua trong `customerAgencyOrder`.
#### Validation
- Kiểm tra tính đúng và đủ của các `input`.
- Nếu `customerIdentity` không được nhập thì thông báo lỗi `customerIdentity is a required field`
- Nếu `customerIdentity` không phải là `string` hoặc là rỗng thì thông báo lỗi `customerIdentity must be a string type`
- Nếu `product` không được nhập hoặc rỗng thì thông báo lỗi `product is a required field`
- Nếu `product.id` không được nhập thì thông báo lỗi `product.id is a required field`
- Nếu `product.id` không phải là string of ObjectId thì thông báo lỗi `product.id must be a string of ObjectId`
- Nếu `product.name` không được nhập thì thông báo lỗi `product.name is a required field`
- Nếu `product.name` không phải là string thì thông báo lỗi `product.name must be a string`
- Nếu `product.image` không phải là string thì thông báo lỗi `product.image must be a string`
- Nếu `variant.id` không được nhập thì thông báo lỗi `variant.id is a required field`
- Nếu `variant.id` không phải là string of ObjectId thì thông báo lỗi `variant.id must be a string of ObjectId`
- Nếu `variant.sku` không được nhập thì thông báo lỗi `variant.sku is a required field`
- Nếu `variant.sku` không phải là string thì thông báo lỗi `variant.sku must be a string`
- Nếu `variant.image` không phải là string thì thông báo lỗi `variant.image must be a string`
- Nếu `variant.price` không được nhập thì thông báo lỗi `variant.price is a required field`
- Nếu `variant.price` không phải là positive number thì thông báo lỗi `variant.price must be a positive number`
- Nếu `customerOrder.id` không được nhập thì thông báo lỗi `customerOrder.id is a required field`
- Nếu `customerOrder.id` không phải là number thì thông báo lỗi `customerOrder.id must be a number`
- Nếu `customerOrder.createdAt` không được nhập thì thông báo lỗi `customerOrder.createdAt is a required field`
- Nếu `customerOrder.createdAt` không phải là Date thì thông báo lỗi `customerOrder.createdAt must be a date type`
- Nếu `customerOrder.completedAt` không được nhập thì thông báo lỗi `customerOrder.completedAt is a required field`
- Nếu `customerOrder.completedAt` không phải là Date thì thông báo lỗi `customerOrder.completedAt must be a date type`
- Nếu `quantity` không được nhập thì thông báo lỗi `quantity is a required field`
- Nếu `quantity` không phải là số nguyên dương thì thông báo lỗi `quantity must be a positive integer number`
#### Process
- Tạo một document mới trong `CustomerProductHistory`
#### Output
- Document đã tạo
#### Input
- customerOders: Danh sách `CustomerOrder` bao gồm các thông tin sau
  - id(string of ObjectId): Mã đơn hàng
  - customerAgencyOrders(string[]): danh sách mã đơn hàng `CustomerAgencyOrder`
  - createdAt(Date): Thời gian đặt hàng
  - updatedAt(Date): Thời gian cập nhật đơn hàng
#### Process
- Mỗi `CustomerOrder`, tìm thông tin đơn hàng `CustomerAgencyOrder` từ `customerOrder.customerAgencyOrders`.
- Mỗi `CustomerAgencyOrder` chứa thông tin của đơn hàng bao gồm:
`customerAgencyOrder.items` chứa thông tin của danh sách sản phẩm: `item.product(id, name, code)`, `item.variant(id)`, `item.price` đơn giá bán của sản phẩm, `item.quantity` số lượng sản phẩm
`customerAgencyOrder.customerId` là Id của `user` nếu khách hàng đặt hàng từ web.
`customerAgencyOrder.customerInfo` là thông tin của khách hàng bao gồm: `customerInfo.phone` số điện thoại đặt hàng của khách hàng, `customerInfo.address` địa chỉ giao hàng, và một số thông tin khác.
- Mỗi `product.id` sẽ tìm được thông tin sản phẩm từ `Product`.
- Cần trích xuất thông tin `product.images`, `product.name` từ thông tin lấy được ở trên, trong đó cần lấy được hình ảnh đầu tiên từ `product.images`, ta sẽ có được thông tin cần để tạo một product customer history là `product(id, image, name)`.
- Tương tự với `variant`, ta có được `variant(id, sku, image)`, đơn giá bán (`variant.price`) có được từ `item.price`
- Với mỗi `customerInfo.phone`, tìm `User` có `user.phone` là `customerInfo.phone`, `Customer` với `userId` là `user.id` và `customerIdentity` sẽ là `customer.id` hoặc `customerInfo.phone` nếu không tìm thấy.
- Với mỗi `item` gọi hàm `createCustomerProductHistory` với input như trên sẽ tạo được một `CustomerProductHistory`
#### Output
- Danh sách `CustomerProductHistory` đã tạo thành công
#### Input
- filter:
  - customerIdentity(string): Số điện thoại khách hàng cần thay đổi
- doc:
  - customerIdentity(string): Mã khách hàng
#### Process
- Tìm tất cả `CustomerProductHistory` ứng với `filter`
- Cập nhật tất cả kết quả tìm được thành `doc`
#### Output
- `CustomerProductHistory` đã cập nhật thành công
#### Crontab
- Chạy lặp lại trong một khoảng thời gian nhất định có thể thay đổi dễ dàng, mặc định là mỗi 5 phút
##### 1. Update CustomerProductHistory from User
- Tìm tất cả khách hàng mới có thời gian đăng ký từ `createdAt` cuối cùng của `CustomerProductHistory` (hoặc âm vô cực nếu không có) đến hiện tại trong `User`
- Nếu không tìm thấy khách hàng nào thì không làm gì cả.
- Nếu có thì với mỗi khách hàng, gọi vào 2 hàm sau:
  - `updateCustomerIdentityInCustomerProductHistory` với `filter` là `{ customerIdentity: số điện thoại khách hàng (user.phone) }` và `doc` là `{ customerIdentity: mã khách hàng (customer.id) }`
  - `updateCustomerIdInCustomerOrder` với `filter` là `{ phone: số điện thoại của khách hàng (user.phone) }` và `doc` là `{ customerId: customer.id }`
  - `updateCustomerIdInCustomerAgencyOrder` với `filter` là `{ phone: số điện thoại của khách hàng (user.phone) }` và `doc` là `{ customerId: customer.id }`
##### 2. Create CustomerProductHistory from CustomerOrder:
- Tìm tất cả các đơn hàng có trạng thái là `COMPLETED` từ `CustomerOrder` với thời gian `updatedAt` lớn hơn thời gian `createdAt` cuối cùng của `CustomerProductHistory` (Nếu không có thì thời gian sẽ là thời gian âm vô cực) và nhỏ hơn hoặc bằng thời gian hiện tại
- `CustomerOrder.id` là ID của đơn hàng
- `CustomerOrder.createdAt` là thời gian đặt hàng hay thời gian tạo đơn hàng.
- `CustomerOrder.updatedAt` là thời gian đơn hàng được chuyển sang trạng thái `COMPLETED`
- `CustomerOrder.customerAgencyOrders` là danh sách ID đơn hàng `CustomerAgencyOrder`
- Gọi hàm `createCustomerProductHistoryFromCustomerOrder` với input là `customerOrders` đã tìm được.
#### Input
- customerIdentity(string): mã định danh người dùng (phone, customerId)
- productId(string of ObjectId): Mã sản phẩm
- variantId(string of ObjectId): Mã phiên bản sản phẩm
- customerOrderId(string of ObjectId): Mã đơn hàng `CustomerOrder`
- since(Date): Lọc theo thời gian hoàn thành `customerOrder.completedAt` từ `since` đến `now` hoặc `until`
- until(Date): Lọc theo thời gian hoàn thành từ `until` trở về `past` hoặc `since`
#### Validation
- Nếu `productId` không phải là string of ObjectId thì thông báo lỗi `productId must be a string of ObjectId`
- Nếu `variantId` không phải là string of ObjectId thì thông báo lỗi `variantId must be a string of ObjectId`
- Nếu `customerOrderId` không phải là string of ObjectId thì thông báo lỗi `variantId must be a string of ObjectId`
#### Process
- Tìm `CustomerProductHistory` ứng với `customerIdentity`, `productId`, `variantId`, `customerOrderId` và trong khoảng từ gian hợp lệ từ `since` đến `until`
#### Output
- Danh sách `CustomerProductHistory` tìm được hoặc rỗng nếu không tìm được.
#### Input
- customerIdentity(string): mã định danh người dùng (phone, customerId)
- productId(string of ObjectId): Mã sản phẩm
- variantId(string of ObjectId): Mã phiên bản sản phẩm
- customerOrderId(string of ObjectId): Mã đơn hàng `CustomerOrder`
- since(Date): Lọc theo thời gian hoàn thành `customerOrder.completedAt` từ `since` đến `now` hoặc `until`
- until(Date): Lọc theo thời gian hoàn thành từ `until` trở về `past` hoặc `since`
#### Validation
- Nếu `productId` không phải là string of ObjectId thì thông báo lỗi `productId must be a string of ObjectId`
- Nếu `variantId` không phải là string of ObjectId thì thông báo lỗi `variantId must be a string of ObjectId`
- Nếu `customerOrderId` không phải là string of ObjectId thì thông báo lỗi `variantId must be a string of ObjectId`
#### Process
- Đếm tất cả `CustomerProductHistory` ứng với `customerIdentity`, `productId`, `variantId`, `customerOrderId` và trong khoảng từ gian hợp lệ từ `since` đến `until`
#### Output
- Một số nguyên không âm cho biết tổng số lượng `CustomerProductHistory`
#### Input
- customerIdentity(string): mã định danh người dùng (phone, customerId)
- productId(string of ObjectId): Mã sản phẩm
- variantId(string of ObjectId): Mã phiên bản sản phẩm
- customerOrderId(string of ObjectId): Mã đơn hàng `CustomerOrder`
- since(Date): Lọc theo thời gian hoàn thành `customerOrder.completedAt` từ `since` đến `now` hoặc `until`
- until(Date): Lọc theo thời gian hoàn thành từ `until` trở về `past` hoặc `since`
#### Validation
- Nếu người dùng chưa đăng nhập thì thông báo lỗi `unauthorized`
- Nếu `customerIdentity` được nhập và người dùng đăng nhập dưới quyền `customer` thì kiểm tra nếu `customerIdentity` khác với `context.user.id` hoặc `context.user.phone` thì thông báo lỗi `permission_denied`
#### Process
- Nếu người dùng đăng nhập dưới quyền `customer` thì `customerIdentity` sẽ được đặt lại là `context.user.id` nếu không được nhập.
- Gọi hàm `getCustomerProductHistories` với input hợp lệ
#### Ouput
- Danh sách `CustomerProductHistory` tìm được hoặc "[]" nếu không tìm được
#### Input
- customerIdentity(string): mã định danh người dùng (phone, customerId)
- productId(string of ObjectId): Mã sản phẩm
- variantId(string of ObjectId): Mã phiên bản sản phẩm
- customerOrderId(string of ObjectId): Mã đơn hàng `CustomerOrder`
- since(Date): Lọc theo thời gian hoàn thành `customerOrder.completedAt` từ `since` đến `now` hoặc `until`
- until(Date): Lọc theo thời gian hoàn thành từ `until` trở về `past` hoặc `since`
#### Validation
- Nếu người dùng chưa đăng nhập thì thông báo lỗi `unauthorized`
- Nếu `customerIdentity` được nhập và người dùng đăng nhập dưới quyền `customer` thì kiểm tra nếu `customerIdentity` khác với `context.user.id` hoặc `context.user.phone` thì thông báo lỗi `permission_denied`
#### Process
- Nếu người dùng đăng nhập dưới quyền `customer` thì `customerIdentity` sẽ được đặt lại là `context.user.id` nếu không được nhập.
- Gọi hàm `countCustomerProductHistories` với input hợp lệ
#### Ouput
- Một số nguyên không âm cho biết tổng số lượng `CustomerProductHistory`

**Comment by nguyenthienthanh** [comment]
Hi @duongdev @lamvh , please review this specification

**Comment by duongdev** [comment]
`numberOfCustomerProductHistories`
`updateCustomerProductHistory` should update `customerOrder`s too
